name: profile updater

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  profile-updater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 履歴をすべて取得する

      - name: Install dependencies
        run: |
          # 必要なパッケージをインストール
          sudo apt update
          sudo apt install -y git mono-runtime

      - uses: kumackey/profile-updater@v1
        with:
          zenn_user_id: joho0724

      - name: Commit and push
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "action@github.com"

          # プッシュ前にリモート変更をリベースで取得
          git pull --rebase origin main || true

          # コミットが必要なら実行
          git add .
          git commit -m "profile updated" || true

          # プッシュを強制的に実行（競合回避）
          git push origin main --force
