name: profile updater

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  profile-updater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 履歴をすべて取得する

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git mono-runtime

      - uses: kumackey/profile-updater@v1
        with:
          zenn_user_id: joho0724

      - name: Commit and push changes
        run: |
          # Gitの設定
          git config --local user.name "GitHub Actions"
          git config --local user.email "action@github.com"

          # リモートの変更を取り込む
          git pull origin main --rebase || true

          # 必要な変更をコミット
          git add .
          git commit -m "profile updated" || true

          # プッシュ
          git push origin main || git pull --rebase origin main && git push origin main
